# Generated by Django 5.1.3 on 2024-11-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profileuser_first_name_profileuser_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
