# Generated by Django 5.1.3 on 2024-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('grandfather_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('saving_account', models.CharField(choices=[('Time deposit', 'Time deposit'), ('Children Saving', 'Children Saving'), ('Business Saving', 'Business Saving')], max_length=50)),
                ('loan_product', models.CharField(blank=True, choices=[('Business Loan', 'Business Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Home Loan', 'Home Loan')], max_length=50, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
