# Generated by Django 5.1.4 on 2025-01-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userformsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equbmembership',
            name='equb_group',
        ),
        migrations.RemoveField(
            model_name='equbmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='EqubGroup',
        ),
        migrations.DeleteModel(
            name='EqubMembership',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
