# Generated by Django 5.1.4 on 2025-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_equbmembership_equb_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
