# Generated by Django 5.1.4 on 2025-01-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog_is_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
