# Generated by Django 5.1.4 on 2025-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_blog_is_latest_remove_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformsubmission',
            name='loan_product',
            field=models.CharField(blank=True, choices=[('Business Loan', 'Business Loan'), ('Salary Loan', 'Salary Loan'), ('Special short-term loans', 'Special short-term loans'), ('Car Loan', 'Car Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Home Loan', 'Home Loan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userformsubmission',
            name='saving_account',
            field=models.CharField(choices=[('Time deposit', 'Time deposit'), ('Children Saving', 'Children Saving'), ('Business Saving', 'Business Saving'), ('Time limit saving', 'Time limit saving'), ('Interest free savings', 'Interest free savings'), ('Savings of women', 'Savings of women')], max_length=50),
        ),
    ]
