# Generated by Django 5.1.4 on 2025-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userformsubmission_loan_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
